#!/bin/bash

BASEDIR=$(dirname "$0")

function launch() {
    printf "Entrez votre mot de passe administrateur pour lancer le jeu (mot de passe de session)\n";
    sudo -S python3 "$BASEDIR/main.py";
}

launch
